### ISSUE TITLE
Pulo.Dev EOL?

### ISSUE THREAD

**Issue by ghost** [pulodev/.github#1]
Hallo, pengurus/admin pulo.dev.

Saya ingin bertanya, apakah pulo.dev sudah berhenti beroperasi? Sebab saya lihat halaman pulo.dev sendiri tidak bisa diakses karena alasan keamanan yang menurut hemat saya sudah beralih dan juga pos twitter berhenti dia 21 May 2023.

Jika demikian, terima kasih telah menyediakan tempat untuk berbagi.

**Comment by hilmanski** [comment]
Halo, saya mohon maaf baru membalas.
Betul, saat ini belum ada bandwith lagi untuk mengurus pulo.dev, mungkin akan berubah ke depannya jika banyak kebutuhan untuk ini dari teman-teman.
